#!/bin/sh

x="Laptop\nLaptop Dual\nVGA\nHDMI\nManual Selection"

y=$(echo -e "$x" | dmenu -i -l 7 -p 'Menu: ')

case "$y" in
    Laptop) xrandr --output LVDS1 --auto --output VGA1 --off;;
    "Laptop Dual") xrandr --output LVDS1 --auto --output VGA1 --auto --right-of LVDS1;;
    VGA) xrandr --output VGA1 --auto --output LVDS1 --off;;
    HDMI) xrandr --output HDMI1 --auto --output LVDS1 --off;;
    "Manual Selection") arandr
esac
